management:
  web:
    exposure:
      include: mappings

spring:
  profiles:
    active: loadInitialData

  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true

  # Konfiguracja JPA (Hibernate)
  jpa:
    hibernate:
      ddl-auto: update # Ustawienie strategii dla Hibernate - w tym przypadku 'update' automatycznie tworzy/aktualizuje tabele w bazie
    show-sql: true # Pokazuje zapytania SQL w konsoli
    properties:
      hibernate:
        format_sql: true # Sformatowane zapytania SQL

  mail:
    host: smtp.wp.pl
    port: 587
    username: paulinakamilawsbmerito@wp.pl
    password: PaulinaKamilaWSB#
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080




